INSERT INTO bwgr."Questions"
	("Id", "Name", "Question", "AttributeId1", "AttributeId2")
VALUES
	(0, 'FILTH', 'Does the character live in squalor and filth?', null, null),
	(1, 'SICKLY', 'Is the character frail and sickly?', null, null),
	(2, 'WOUND', 'Was the character severely wounded in the past?', null, null),
	(3, 'TORTURE', 'Has the character been tortured?', null, null),
	(4, 'ENSLAVED', 'Has the character been enslaved?', null, null),
	(5, 'ACTIVE', 'Is the character athletic and active?', null, null),
	(6, 'HAPPY', 'Does the character live in a really clean and happy place, like the hills in The Sound of Music?', null, null),
	(7, 'SOLDIER', 'Has the character taken a conscript, soldier, bandit, squire, or knight type lifepath?', null, null),
	(8, 'KILLER', 'Has the character ever murdered or killed with his own hand more than once?', null, null),
	(9, 'BEATEN', 'Has the character been beaten terribly over time?', null, null),
	(10, 'SHELTER', 'Has the character led a sheltered life, free from violance and pain?', null, null),
	(11, 'COMPETITIVE', 'Has the character been raised in a competitive (but non-violent) culture —sports, debate, strategy games, courting?', null, null),
	(12, 'BIRTH', 'Has the character given birth to a child?', null, null),
	(13, 'GIFTED', 'Is the character Gifted or Faithful or an equivalent?', null, null),
	(14, 'COVET', 'Has the character ever coveted something owned by another?', 12, null),
	(15, 'STOLE', 'Has the character ever stolen something they coveted?', 12, null),
	(16, 'STOLEN', 'Has the Dwarf ever had their prized treasure stolen from them?', 12, null),
	(17, 'MASTERCRAFT', 'Has the character ever been in the presence of the master craftmanship of the Dwarven Fathers?', 12, null),
	(18, 'POSSESSION', 'Has the character witnessed an outsider (Elf, Human, Orc, Roden, etc.) in possession of a work of Dwarven Art?', 12, null),
	(19, 'TRAGEDY', 'Does the character''s history include tragedy?', 13, null),
	(20, 'OUTSIDER', 'Did the character has lived amonh non-Elven people?', 13, null),
	(21, 'BETRAYAL', 'Has the character been betrayed by their friends?', 13, 14),
	(22, 'LOVESICK', 'Is the character lovesick or broken hearted?', 13, 14),
	(23, 'ABANDON', 'Has the character been abandoned by those he held dear?', 13, 14),
	(24, 'ABUSED', 'Has the character been abused?', 13, 14),
	(25, 'RESPECT', 'Does the character still respect or admire someone on the other side?', 13, 14),
	(26, 'LOVE', 'Does the character still love someone on the other side?', 13, 14),
	(27, 'TRUST', 'Does the character trust the their God the most?', 15, null),
	(28, 'CONSULT', 'When in danger, does the character consult their God for aid?', 15, null),
	(29, 'SERVE', 'Does the character think that ultimately only with their God them can best serve their allies?', 15, null),
	(30, 'DEADTRUST', 'Does the character trust the their Dead God the most?', 16, null),
	(31, 'DEADCONSULT', 'When in danger, does the character consult their Dead God for aid?', 16, null),
	(32, 'DEADSERVE', 'Does the character think that ultimately only with their Dead God they can best serve their allies?', 16, null),
	(33, 'SLAVE', 'Have the character been to slave to another?', 17, null),
	(34, 'FRATRICIDE', 'Have the character ever killed their superior or parents?', 17, null),
	(35, 'HOBGOBLIN', 'Have the character ever attempted to command a unit of goblins in battle?', 17, null),
	(36, 'MASTER', 'Is their master the God of Darkness and Blood?', 18, null),
	(37, 'FATE', 'Does the Darkness and Blood controls their fate?', 18, null),
	(38, 'WELLSPRING', 'Is the Darkness and Blood the wellspring of their power?', 18, null),
	(39, 'PRAY', 'Have the character has ever prayed alone at night to remote, unholy gods to aid him?', 20, null),
	(40, 'PACT', 'Have the the character has ever entered into a pact with a demon?', 20, null);
