/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BwgrAbilities {
  AbilityTypeId: number;
  Challenging: number | null;
  Cycle: number | null;
  Difficult: number | null;
  HasShades: boolean;
  Id: Generated<number>;
  Name: string;
  RequiredTraitId: number | null;
  Routine: number | null;
}

export interface BwgrAbilityTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrActionResolutionTypes {
  Id: Generated<number>;
  Name: string;
  NameLong: string;
}

export interface BwgrAgePools {
  Id: Generated<number>;
  MentalPool: number;
  MinAge: number;
  PhysicalPool: number;
  StockId: Generated<number>;
}

export interface BwgrAltSpellAreaOfEffectFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
  SubFacet: string | null;
}

export interface BwgrAltSpellDurationFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
  SubFacet: string | null;
}

export interface BwgrAltSpellFacetTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrAltSpellHigherElementFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrAltSpellLawFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrAltSpellLowerElementFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrAltSpellOriginFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrAltSpellPrimeElementFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrDistanceUnits {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrDuelOfWitsActionResolutions {
  AbilityId: number | null;
  ActionId: number;
  Id: Generated<number>;
  IsAgainstSkill: boolean | null;
  Obstacle: number | null;
  OpposingAbilityId: number | null;
  OpposingActionId: number;
  OpposingModifier: number | null;
  OpposingSkillId: number | null;
  ResolutionTypeId: number;
  SkillId: number | null;
}

export interface BwgrDuelOfWitsActions {
  Effect: string | null;
  Id: Generated<number>;
  Name: string;
  SpeakingThePart: string | null;
  Special: string | null;
}

export interface BwgrDuelOfWitsActionTests {
  AbilityId: number | null;
  ActionId: number;
  Id: Generated<number>;
  SkillId: number | null;
}

export interface BwgrFightActionGroups {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrFightActionResolutions {
  AbilityId: number | null;
  ActionId: number;
  Id: Generated<number>;
  IsAgainstSkill: boolean | null;
  Obstacle: number | null;
  OpposingAbilityId: number | null;
  OpposingActionId: number;
  OpposingModifier: number | null;
  OpposingSkillId: number | null;
  ResolutionTypeId: number;
  SkillId: number | null;
}

export interface BwgrFightActions {
  ActionCost: number | null;
  CountsAsNoAction: boolean;
  Effect: string | null;
  GroupId: number;
  Id: Generated<number>;
  Name: string;
  Restrictions: string | null;
  Special: string | null;
  TestExtra: string | null;
}

export interface BwgrFightActionTests {
  AbilityId: number | null;
  ActionId: number;
  Id: number;
  SkillId: number | null;
}

export interface BwgrLifepathCompanions {
  CompanionName: string;
  GivesSkills: boolean;
  GSPMultiplier: number;
  LifepathId: number;
  LSPMultiplier: number;
  RPMultiplier: number;
}

export interface BwgrLifepathCompanionSettings {
  CompanionSettingId: number;
  LifepathId: number;
}

export interface BwgrLifepathLeads {
  LifepathId: number;
  SettingId: number;
}

export interface BwgrLifepathRequirementItems {
  AttributeId: number | null;
  ForCompanion: boolean;
  Id: Generated<number>;
  LifepathId: number | null;
  Max: number | null;
  Min: number | null;
  RequirementId: number;
  RequirementTypeId: number;
  SettingId: number | null;
  SkillId: number | null;
  TraitId: number | null;
}

export interface BwgrLifepathRequirements {
  FulfillmentAmount: number;
  Id: Generated<number>;
  LifepathId: number;
  LogicTypeId: number;
  MustFulfill: boolean;
}

export interface BwgrLifepaths {
  Born: boolean;
  EitherPool: number;
  GeneralSkillPool: number;
  HalfGSPFromPrev: boolean;
  HalfLSPFromPrev: boolean;
  HalfRPFromPrev: boolean;
  Id: Generated<number>;
  IsGSPMultiplier: boolean;
  IsLSPMultiplier: boolean;
  IsRPMultiplier: boolean;
  LifepathSkillPool: number;
  MentalPool: number;
  Name: string;
  PhysicalPool: number;
  RequirementText: string | null;
  ResourcePoints: number;
  SettingId: number;
  StockId: number;
  TraitPool: number;
  Years: number[];
}

export interface BwgrLifepathSkills {
  Index: number;
  LifepathId: number;
  SkillId: number;
}

export interface BwgrLifepathTraits {
  Index: number;
  LifepathId: number;
  TraitId: number;
}

export interface BwgrLogicTypes {
  Id: number;
  Name: string;
}

export interface BwgrQuestions {
  AttributeId1: number | null;
  AttributeId2: number | null;
  Id: Generated<number>;
  Name: string;
  Question: string;
}

export interface BwgrRangeAndCoverActionGroups {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrRangeAndCoverActionResolutions {
  AbilityId: number | null;
  ActionId: number;
  Id: Generated<number>;
  IsAgainstSkill: boolean | null;
  Obstacle: number | null;
  OpposingAbilityId: number | null;
  OpposingActionId: number;
  OpposingModifier: number | null;
  OpposingSkillId: number | null;
  ResolutionTypeId: number;
  SkillId: number | null;
}

export interface BwgrRangeAndCoverActions {
  Effect: string;
  GroupId: number;
  However: string | null;
  Id: Generated<number>;
  IsOpenEnded: boolean;
  Modifier: number;
  Name: string;
  SpecialAction: string | null;
  SpecialRestriction: string | null;
  UseFoRKs: boolean;
  UsePositionAdvantage: boolean;
  UseStrideAdvantage: boolean;
  UseWeaponRangeAdvantage: boolean;
}

export interface BwgrRequirementItemTypes {
  Id: number;
  Name: string;
}

export interface BwgrResourceCosts {
  Cost: number;
  Description: string | null;
  Id: number;
  ResourceId: number;
}

export interface BwgrResourceMagicDetails {
  Actions: number;
  ActionsMultiply: boolean;
  AreaOfEffectId: number;
  AreaOfEffectModifierId: number | null;
  AreaOfEffectUnitId: number | null;
  DurationId: number;
  DurationUnitId: number | null;
  Element1Id: number;
  Element2Id: number | null;
  Element3Id: number | null;
  Id: Generated<number>;
  Impetus1Id: number;
  Impetus2Id: number | null;
  OriginId: number;
  OriginModifierId: number | null;
  ResourceId: number;
}

export interface BwgrResourceMagicObstacles {
  Description: string | null;
  Id: Generated<number>;
  Obstacle: number | null;
  ObstacleAbility1Id: number | null;
  ObstacleAbility2Id: number | null;
  ObstacleCaret: boolean;
  ResourceId: number;
}

export interface BwgrResourceModifiers {
  Cost: number;
  Description: string | null;
  Id: number;
  IsPerCost: boolean;
  ResourceId: number;
}

export interface BwgrResources {
  Description: string | null;
  Id: Generated<number>;
  Name: string;
  ResourceTypeId: number;
  StockId: number;
  VariableCost: boolean;
}

export interface BwgrResourceTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrRulesetExpansions {
  ExpansionId: string;
  RulesetId: string;
}

export interface BwgrRulesetLifepaths {
  LifepathId: number;
  RulesetId: string;
}

export interface BwgrRulesetResources {
  ResourceId: number;
  RulesetId: string;
}

export interface BwgrRulesets {
  Id: string;
  IsExpansion: boolean;
  IsOfficial: boolean;
  IsPublic: boolean;
  Name: string;
  User: string | null;
}

export interface BwgrRulesetSettings {
  RulesetId: string;
  SettingId: number;
}

export interface BwgrRulesetSkills {
  RulesetId: string;
  SkillId: number;
}

export interface BwgrRulesetStocks {
  RulesetId: string;
  StockId: number;
}

export interface BwgrRulesetTraits {
  RulesetId: string;
  TraitId: number;
}

export interface BwgrSettings {
  Id: Generated<number>;
  IsSubsetting: boolean;
  Name: string;
  NameShort: string;
  StockId: number;
}

export interface BwgrSkillCategories {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrSkills {
  CategoryId: number;
  Description: string | null;
  DontList: boolean;
  Id: Generated<number>;
  IsMagical: boolean;
  IsTraining: boolean;
  Name: string;
  RestrictionAbilityId: number | null;
  RestrictionOnlyStockId: number | null;
  RestrictionWhenBurning: boolean | null;
  Root1Id: number | null;
  Root2Id: number | null;
  StockId: number | null;
  ToolDescription: string | null;
  ToolTypeId: number | null;
  TypeId: number;
}

export interface BwgrSkillSubskills {
  SkillId: number;
  SubskillId: number;
}

export interface BwgrSkillToolTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrSkillTypes {
  Challenging: number;
  Cycle: number;
  Difficult: number;
  Id: Generated<number>;
  Name: string;
  Routine: number;
}

export interface BwgrSpellAreaOfEffectFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrSpellDurationFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrSpellElementFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrSpellFacetTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrSpellImpetusFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrSpellOriginFacets {
  Actions: number;
  Id: Generated<number>;
  Name: string;
  Obstacle: number;
  Resource: number;
}

export interface BwgrStocks {
  Id: Generated<number>;
  Name: string;
  NamePlural: string;
  Stride: number;
}

export interface BwgrTimeUnits {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrTraitCategories {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrTraits {
  CategoryId: number;
  Cost: number;
  Description: string | null;
  Id: Generated<number>;
  Name: string;
  StockId: number | null;
  TypeId: number;
}

export interface BwgrTraitTypes {
  Id: Generated<number>;
  Name: string;
}

export interface BwgrUnitModifiers {
  Id: Generated<number>;
  Name: string;
}

export interface SysMigrations {
  name: string;
  runAt: Generated<Timestamp>;
}

export interface UsrUserAccess {
  Id: Generated<number>;
  UserAccessTypeId: number;
  UserId: string;
}

export interface UsrUserAccessTypes {
  Id: Generated<number>;
  Name: string | null;
}

export interface UsrUserRoles {
  Id: Generated<number>;
  Name: string | null;
}

export interface UsrUsers {
  CreatedAt: Generated<Timestamp>;
  Email: string;
  Enabled: Generated<boolean>;
  Id: Generated<string>;
  LastSigninAt: Timestamp | null;
  Password: string;
  Role: Generated<number>;
  Username: string;
}

export interface UsrUserSessions {
  expire: Timestamp;
  sess: Json;
  sid: string;
}

export interface DB {
  "bwgr.Abilities": BwgrAbilities;
  "bwgr.AbilityTypes": BwgrAbilityTypes;
  "bwgr.ActionResolutionTypes": BwgrActionResolutionTypes;
  "bwgr.AgePools": BwgrAgePools;
  "bwgr.AltSpellAreaOfEffectFacets": BwgrAltSpellAreaOfEffectFacets;
  "bwgr.AltSpellDurationFacets": BwgrAltSpellDurationFacets;
  "bwgr.AltSpellFacetTypes": BwgrAltSpellFacetTypes;
  "bwgr.AltSpellHigherElementFacets": BwgrAltSpellHigherElementFacets;
  "bwgr.AltSpellLawFacets": BwgrAltSpellLawFacets;
  "bwgr.AltSpellLowerElementFacets": BwgrAltSpellLowerElementFacets;
  "bwgr.AltSpellOriginFacets": BwgrAltSpellOriginFacets;
  "bwgr.AltSpellPrimeElementFacets": BwgrAltSpellPrimeElementFacets;
  "bwgr.DistanceUnits": BwgrDistanceUnits;
  "bwgr.DuelOfWitsActionResolutions": BwgrDuelOfWitsActionResolutions;
  "bwgr.DuelOfWitsActions": BwgrDuelOfWitsActions;
  "bwgr.DuelOfWitsActionTests": BwgrDuelOfWitsActionTests;
  "bwgr.FightActionGroups": BwgrFightActionGroups;
  "bwgr.FightActionResolutions": BwgrFightActionResolutions;
  "bwgr.FightActions": BwgrFightActions;
  "bwgr.FightActionTests": BwgrFightActionTests;
  "bwgr.LifepathCompanions": BwgrLifepathCompanions;
  "bwgr.LifepathCompanionSettings": BwgrLifepathCompanionSettings;
  "bwgr.LifepathLeads": BwgrLifepathLeads;
  "bwgr.LifepathRequirementItems": BwgrLifepathRequirementItems;
  "bwgr.LifepathRequirements": BwgrLifepathRequirements;
  "bwgr.Lifepaths": BwgrLifepaths;
  "bwgr.LifepathSkills": BwgrLifepathSkills;
  "bwgr.LifepathTraits": BwgrLifepathTraits;
  "bwgr.LogicTypes": BwgrLogicTypes;
  "bwgr.Questions": BwgrQuestions;
  "bwgr.RangeAndCoverActionGroups": BwgrRangeAndCoverActionGroups;
  "bwgr.RangeAndCoverActionResolutions": BwgrRangeAndCoverActionResolutions;
  "bwgr.RangeAndCoverActions": BwgrRangeAndCoverActions;
  "bwgr.RequirementItemTypes": BwgrRequirementItemTypes;
  "bwgr.ResourceCosts": BwgrResourceCosts;
  "bwgr.ResourceMagicDetails": BwgrResourceMagicDetails;
  "bwgr.ResourceMagicObstacles": BwgrResourceMagicObstacles;
  "bwgr.ResourceModifiers": BwgrResourceModifiers;
  "bwgr.Resources": BwgrResources;
  "bwgr.ResourceTypes": BwgrResourceTypes;
  "bwgr.RulesetExpansions": BwgrRulesetExpansions;
  "bwgr.RulesetLifepaths": BwgrRulesetLifepaths;
  "bwgr.RulesetResources": BwgrRulesetResources;
  "bwgr.Rulesets": BwgrRulesets;
  "bwgr.RulesetSettings": BwgrRulesetSettings;
  "bwgr.RulesetSkills": BwgrRulesetSkills;
  "bwgr.RulesetStocks": BwgrRulesetStocks;
  "bwgr.RulesetTraits": BwgrRulesetTraits;
  "bwgr.Settings": BwgrSettings;
  "bwgr.SkillCategories": BwgrSkillCategories;
  "bwgr.Skills": BwgrSkills;
  "bwgr.SkillSubskills": BwgrSkillSubskills;
  "bwgr.SkillToolTypes": BwgrSkillToolTypes;
  "bwgr.SkillTypes": BwgrSkillTypes;
  "bwgr.SpellAreaOfEffectFacets": BwgrSpellAreaOfEffectFacets;
  "bwgr.SpellDurationFacets": BwgrSpellDurationFacets;
  "bwgr.SpellElementFacets": BwgrSpellElementFacets;
  "bwgr.SpellFacetTypes": BwgrSpellFacetTypes;
  "bwgr.SpellImpetusFacets": BwgrSpellImpetusFacets;
  "bwgr.SpellOriginFacets": BwgrSpellOriginFacets;
  "bwgr.Stocks": BwgrStocks;
  "bwgr.TimeUnits": BwgrTimeUnits;
  "bwgr.TraitCategories": BwgrTraitCategories;
  "bwgr.Traits": BwgrTraits;
  "bwgr.TraitTypes": BwgrTraitTypes;
  "bwgr.UnitModifiers": BwgrUnitModifiers;
  "sys.Migrations": SysMigrations;
  "usr.UserAccess": UsrUserAccess;
  "usr.UserAccessTypes": UsrUserAccessTypes;
  "usr.UserRoles": UsrUserRoles;
  "usr.Users": UsrUsers;
  "usr.UserSessions": UsrUserSessions;
}
