import type { Metadata } from "next";
import type { JSX } from "react";

import "./globals.css";


// eslint-disable-next-line @typescript-eslint/naming-convention, react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>): JSX.Element {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
