
export const Callings: HeartCalling[] = [
	{
		name: "Adventure",
		description: "The City Above holds no more excitement for you. In the City Beneath, on the knife-edge between real and unreal, you can be who you really are.",
		ability: {
			name: "Legendary",
			type: "Core",
			description: "You strive to live up to the stories that they'll tell of your exploits.",
			effect: "When you gain a minor advance, refresh D6. When you gain a major advance, refresh D8."
		},
		questions: [
			{ rest: "What drove you out of the City Above?" },
			{ rest: "You and another player character barely escaped from a dangerous situation recently. Who was it and what happened?" },
			{ rest: "Recently, you and another character returned from a delve with an item for a wealthy patron. They wouldn't give it up —why, and what was it?" },
			{ rest: "What's the most dangerous beast or individual you've heard tell of, and why haven't you defeated them yet?" }
		],
		beats: [
			{ description: "Charm someone with tales of your exploits.", type: "Minor" },
			{ description: "Engage in reckless abandon with drink, drugs or sex.", type: "Minor" },
			{ description: "Slay a beast that drops resources of D10 or higher.", type: "Minor" },
			{ description: "Access a haven in tier 2 of the Heart.", type: "Minor" },
			{ description: "Take Major Blood fallout.", type: "Minor" },
			{ description: "Take Major Fortune fallout.", type: "Minor" },
			{ description: "Defeat a powerful foe one-on-one.", type: "Minor" },
			{ description: "Help an important or influential figure in a haven.", type: "Minor" },
			{ description: "Refuse to back down when it would be beneficial to do so.", type: "Minor" },
			{ description: "Establish a connection.", type: "Minor" },
			{ description: "Get in trouble with the Hounds.", type: "Minor" },
			{ description: "Rescue someone from peril.", type: "Minor" },
			{ description: "Make a dramatic entrance that's a Risky action.", type: "Minor" },
			{ description: "Claim a resource of at least D10 from a dangerous location.", type: "Minor" },
			{ description: "Defend a haven from attack.", type: "Minor" },
			{ description: "Have at least three havens know your name, for good or ill.", type: "Minor" },
			{ description: "Rush into danger before anyone else.", type: "Minor" },
			{ description: "Have a cocktail, fighting move or legendary beast named after you.", type: "Minor" },
			{ description: "Go somewhere where no-one else has stepped foot for at least a century.", type: "Minor" },
			{ description: "Win an unarmed brawl in a haven.", type: "Minor" },
			{ description: "Kick someone off a tall structure (they really deserved it).", type: "Minor" },
			{ description: "Acquire a rare or powerful (D12 value) item, preferably magic.", type: "Major" },
			{ description: "Slay a beast that's at least five times your size.", type: "Major" },
			{ description: "Have a landmark or connection named after you.", type: "Major" },
			{ description: "Upgrade a haunt to D12.", type: "Major" },
			{ description: "Save a haven from destruction or doom.", type: "Major" },
			{ description: "Connect three havens to one another with permanent paths.", type: "Major" },
			{ description: "Successfully perform a Dangerous action that saves the day.", type: "Major" },
			{ description: "Catalogue your exploits for an extended period; either do it yourself or hire a bard.", type: "Major" },
			{ description: "Lead a group or organisation (other than your delving party).", type: "Major" },
			{ description: "Successfully lead, and take full credit for, a delve that takes you to Tier 3 or deeper.", type: "Major" },
			{ description: "Reach Tier 4 of the Heart.", type: "Zenith" },
			{ description: "Lead a haven to prosperity.", type: "Zenith" }
		],
		trinkets: [
			"Pulp novel loosely based on your exploits",
			"Mouth organ",
			"Spidersilk scarf in a dashing colour",
			"Inaccurate map of the Heart you bought off some guy in Derelictus",
			"Copy of “RAVENOUS SHE-WITCHES OF HALLOW”, a best-selling sensationalist book",
			"Paper and sketching charcoal",
			"Fake “Abomination-hunting” license",
			"Unpunched Vermissian ticket used as a good-luck charm",
			"Letters from your mum asking when you're going to come home",
			"Expensive kohl eyeliner and pocket-mirror"
		]
	},
	{
		name: "Enlightenment",
		description: "Everyone said that what you intended to do was impossible, but you've never let “possibility” slow you down. You're looking for secrets hidden deep within the earth. You know that the Heart holds the answers to all your questions; no matter what it takes, you'll get them.",
		ability: {
			name: "Unorthodox Methods",
			type: "Core",
			description: "You blend together method and madness in pursuit of your goals",
			effect: "Gain the Discern skill. Once per session, before you roll dice to resolve an action, instead state that your result is a 6. You succeed but take stress."
		},
		questions: [
			{ rest: "What “impossible” thing are you attempting to achieve in the City Beneath?" },
			{ rest: "What's the first step on your journey?" },
			{ rest: "Choose another player character. They've been invaluable in your journey so far. What have you learned from them?" },
			{ rest: "Choose another player character. You know they're hiding secrets from you —why do you suspect they're doing this?" }
		],
		beats: [
			{ description: "Allude to the events that led you to seek forbidden knowledge to achieve an impossible task.", type: "Minor" },
			{ description: "Put the acquisition of knowledge above preserving the lives of your allies.", type: "Minor" },
			{ description: "Gain access to knowledge that someone tried to conceal.", type: "Minor" },
			{ description: "Gain favour with a faction that can help you learn more about your goal.", type: "Minor" },
			{ description: "Take Minor Mind fallout.", type: "Minor" },
			{ description: "Destroy evidence or rhetoric that proves your task to be impossible.", type: "Minor" },
			{ description: "Sell or sacrifice a D8 or higher resource to secure a secret.", type: "Minor" },
			{ description: "Reach a landmark on tier 3 of the Heart.", type: "Minor" },
			{ description: "Find a helpful text.", type: "Minor" },
			{ description: "Succeed at a task that someone else has recently failed to achieve.", type: "Minor" },
			{ description: "Mark D8 stress to an NPC bond and describe what happens.", type: "Minor" },
			{ description: "Acquire an NPC bond who has access to useful information.", type: "Minor" },
			{ description: "Establish a connection on a delve.", type: "Minor" },
			{ description: "Take Minor Supplies fallout.", type: "Minor" },
			{ description: "Flee from combat or a similarly dangerous situation, or hide until it all blows over.", type: "Minor" },
			{ description: "Release your shocking findings in a journal published in the City Above.", type: "Minor" },
			{ description: "Meet someone from your old life who's trying to get you to give up on your quest.", type: "Minor" },
			{ description: "Dissect something or interrogate someone that can shed light on your task.", type: "Minor" },
			{ description: "Buy some cutting-edge, experimental or finely-made equipment and use it on a delve.", type: "Minor" },
			{ description: "Take Major Mind fallout.", type: "Major" },
			{ description: "Kill someone who is trying to stop you from claiming knowledge.", type: "Major" },
			{ description: "Sell or sacrifice a D12 resource to secure a secret.", type: "Major" },
			{ description: "Destroy a haunt to learn more about your task.", type: "Major" },
			{ description: "Gain authority within a faction that you can use to learn more about your goal.", type: "Major" },
			{ description: "Find a source of knowledge on Tier 3 of the Heart.", type: "Major" },
			{ description: "Take Major Supplies fallout.", type: "Major" },
			{ description: "Acquire a renowned piece of equipment.", type: "Major" },
			{ description: "Attract a protégé who's read your work and is determined to learn more.", type: "Major" },
			{ description: "Explore a mysterious tower whilst on a delve (this increases the difficulty of the delve by D12).", type: "Major" },
			{ description: "Find the final secret you have so desperately sought and use it to solve your impossible task.", type: "Zenith" },
			{ description: "Find the final secret you have so desperately sought and destroy it so no one else can know of it.", type: "Zenith" }
		],
		trinkets: [
			"Set of fragile magnifying lenses",
			"Book of handwritten theories and observations",
			"Portable alchemy kit in a leather box",
			"Dried dream-mushrooms",
			"Heady incense sticks that burn dirty-blue smoke",
			"Bundled-up red-string-and-pins collage identifying the fools who tried to stop you",
			"List of people who are Going To Pay, some names crossed out",
			"Bag of heavy glass fortune stones",
			"Taxidermied owl (name them)",
			"Imported book of meditative stances and recipes to cleanse your spirit"
		]
	},
	{
		name: "Forced",
		description: "You don't want to be down here, but you don't have any choice. You're a prisoner, an initiate to a cult or someone's blackmailing you.",
		ability: {
			name: "Collateral",
			type: "Core",
			description: "You have a knack for getting behind someone else when things kick off.",
			effect: "Once per session, allocate stress to the nearest friendly target (PC or NPC) instead of marking it yourself."
		},
		questions: [
			{ rest: "Who, or what, are your masters?" },
			{ rest: "What do your masters want?" },
			{ rest: "How are your masters maintaining power over you?" },
			{ rest: "How do your masters contact you?" },
			{ rest: "Choose another player character. They have history with your masters too. What's their relationship?" }
		],
		beats: [
			{ description: "Receive orders from your masters.", type: "Minor" },
			{ description: "Follow orders from your masters, even though they put you at risk.", type: "Minor" },
			{ description: "Rebel against your orders, even though this puts you at risk.", type: "Minor" },
			{ description: "Forge a friendship or romantic relationship with an NPC.", type: "Minor" },
			{ description: "Get into trouble as someone discovers your chequered past.", type: "Minor" },
			{ description: "Betray someone because of your true nature.", type: "Minor" },
			{ description: "Take Minor Fortune fallout.", type: "Minor" },
			{ description: "Do something dangerous to conceal your past.", type: "Minor" },
			{ description: "Invoke your masters' name to get what you want.", type: "Minor" },
			{ description: "As a result of using the COLLATERAL ability, an NPC is taken out of action or a PC suffers fallout.", type: "Minor" },
			{ description: "Find a sanctuary where your masters cannot reach you.", type: "Minor" },
			{ description: "Rescue an NPC from trouble that you caused.", type: "Minor" },
			{ description: "Receive a time-critical mission that leads you away from your other objectives.", type: "Minor" },
			{ description: "Receive aid from someone reprehensible who's in the employ of your master.", type: "Minor" },
			{ description: "Send a requested resource (D8 or higher) back to your master rather than using it yourself.", type: "Minor" },
			{ description: "Perform a seemingly unconnected action for your masters that has grim consequences.", type: "Minor" },
			{ description: "Cover up a crime that someone else committed on behalf of your masters.", type: "Minor" },
			{ description: "Claim you're doing something on behalf of your masters when in fact it's for your own ends.", type: "Minor" },
			{ description: "Involve an NPC in your master's schemes.", type: "Minor" },
			{ description: "Do a favour for someone to gain leverage over them.", type: "Minor" },
			{ description: "Destroy something important to your masters.", type: "Major" },
			{ description: "Learn or possess something that lessens the control your masters have over you.", type: "Major" },
			{ description: "Perform a truly reprehensible act on behalf of your masters.", type: "Major" },
			{ description: "Suffer the consequences of refusing to perform an important act on behalf of your masters.", type: "Major" },
			{ description: "Take Major Fortune fallout.", type: "Major" },
			{ description: "An important or beloved NPC dies after you bring them into your master's schemes.", type: "Major" },
			{ description: "Thanks to your actions, a haven is pitched into deadly chaos.", type: "Major" },
			{ description: "Coerce an important or beloved NPC into undertaking a task they don't want to do.", type: "Major" },
			{ description: "Aid another person, who you know and hate, that is also in the employ of your masters.", type: "Major" },
			{ description: "Complete a major objective for your master —something taking at least two sessions to achieve.", type: "Major" },
			{ description: "End the control your master has over you.", type: "Zenith" },
			{ description: "Take bloody revenge on your master.", type: "Zenith" }
		],
		trinkets: [
			"Daguerreotype of your son",
			"Moonsilver collar",
			"Signed contract detailing your “employment”",
			"Matchbook from The Manticore, an up-Spire casino",
			"Subjugation sliver implanted in your neck",
			"Guild brand on your upper arm",
			"Deed to an apartment in Ivory Row up-Spire",
			"Mark on your chest where your soul used to be, before you sold it",
			"Your master's sigil, wrought from iron",
			"Codebook showing you how and where to make your reports"
		]
	},
	{
		name: "Heartsong",
		description: "When you sleep, you dream of the Heart. You're half-mad with glimpses of knowledge; mad enough to go ever deeper into the undercity, looking for revelations.",
		ability: {
			name: "In the Blood",
			type: "Core",
			description: "You move through the Heart as if blessed.",
			effect: "+1 Echo Protection. Once per situation, when you take stress to any resistance other than Echo, allocate it to Echo."
		},
		questions: [
			{ rest: "Which three images, symbols, people or creatures do you repeatedly see when you dream?" },
			{ rest: "What signs do you look for to recognise where the Heart is strongest?" },
			{ rest: "You recently witnessed an unearthly sight with another player character. Who was it, what happened and how did they react?" },
			{ rest: "Your connection to the Heart has touched you in some way. How does that manifest?" }
		],
		beats: [
			{ description: "Following a long ritual, name The Heart. Only refer to it by this name from now on.", type: "Minor" },
			{ description: "Take Minor Echo fallout.", type: "Minor" },
			{ description: "See something from your dreams in the real world.", type: "Minor" },
			{ description: "Consume something of the Heart (eat the flesh of a heartsblood beast, etc).", type: "Minor" },
			{ description: "Be rendered helpless in the Heart for an hour or more.", type: "Minor" },
			{ description: "Perform a rite at a place of power (Tier 2 or deeper).", type: "Minor" },
			{ description: "Damage or sabotage a haven, letting the Heart in.", type: "Minor" },
			{ description: "Sacrifice something you love to the Heart.", type: "Minor" },
			{ description: "Allow something dangerous of the Heart to live when you could have killed it.", type: "Minor" },
			{ description: "Let your curiosity lead you into danger.", type: "Minor" },
			{ description: "Undergo a trance-like vision that lasts for hours.", type: "Minor" },
			{ description: "Communicate with something of the Heart.", type: "Minor" },
			{ description: "Witness an emissary of the Heart Itself.", type: "Minor" },
			{ description: "Experience a pulse —the changing of the Heart from one state to another— first-hand.", type: "Minor" },
			{ description: "Receive insight from a witch, a heartsblooded person or something stranger still.", type: "Minor" },
			{ description: "Gain information on why you have been chosen by the Heart.", type: "Minor" },
			{ description: "Receive a strange surgical implant or heartsblood transfusion.", type: "Minor" },
			{ description: "Build a shrine to the Heart somewhere important.", type: "Minor" },
			{ description: "Terrify or intrigue an NPC with your obsession.", type: "Minor" },
			{ description: "Perform an act of service to an NPC witch.", type: "Minor" },
			{ description: "Shelter someone touched by the Heart from persecution.", type: "Minor" },
			{ description: "Find a heart-touched sapling on a delve and bring it back to a haven for planting.", type: "Minor" },
			{ description: "Convince the party to collect Cursed resources on a delve, adding D6 to the delve's resistance.", type: "Minor" },
			{ description: "Take Major Echo fallout.", type: "Major" },
			{ description: "Perform a rite at a place of power (Tier 3 or deeper).", type: "Major" },
			{ description: "Sacrifice someone important to the Heart.", type: "Major" },
			{ description: "Establish a bond with a hearts-blood beast (Tier 2 or deeper).", type: "Major" },
			{ description: "Show the truth of the Heart's majesty to an outsider (Tier 2 or deeper).", type: "Major" },
			{ description: "Meet and learn from an emissary of the Heart.", type: "Major" },
			{ description: "Destroy a haven, returning the land to the Heart.", type: "Major" },
			{ description: "One of your bonds takes Critical fallout thanks to your actions.", type: "Major" },
			{ description: "Deliver a crucial message on behalf of the Heart.", type: "Major" },
			{ description: "Visit three Vermissian Stations.", type: "Major" },
			{ description: "Become one with the Heart, and bind your essence to it.", type: "Zenith" },
			{ description: "Break the hold that the Heart has over you, ripping it from your body and spirit.", type: "Zenith" }
		],
		trinkets: [
			"Ink-blotted dream journal with maps of places you saw when you were asleep",
			"Bag of bitter stimulant pastilles",
			"Steel syringe and opiate powder",
			"The word “THEOLOSIAN” growing over your upper chest",
			"Barely-viable homonculus you shamefully coughed up or excised (name it)",
			"Twenty sketches of the man you're convinced you're going to meet down here, all made by different artists",
			"Signed copy of BEYOND THE EDGE OF MADNESS: A Year In The Heart by Gris Hanneman",
			"Mandala made from hollow crow bones",
			"Mad, impressionist votive image of a Witch",
			"Greenish candles that help you sleep a dream less sleep (sometimes)"
		]
	},
	{
		name: "Penitent",
		description: "You betrayed the trust of your order. Due to negligence, cowardice or malice, you caused them great harm. Now, wracked with guilt, you have sworn to make amends by venturing deep into the Heart and performing acts in service of your order.",
		ability: {
			name: "Not Yet",
			type: "Core",
			description: "Your willpower, fuelled with guilt, is legendary.",
			effect: "Once per session, activate this ability to avoid suffering negative effects from Blood or Mind fallout for the remainder of the situation."
		},
		questions: [
			{ rest: "What marks your order out from others like it?" },
			{ rest: "What evidence of your failings is visible in the City Beneath?" },
			{ rest: "Pick one of the other player characters; they were present at your betrayal. How were they involved?" },
			{ rest: "Pick one of the other player characters; you look up to them as an example of how to live one's life. What inspired this?" }
		],
		beats: [
			{ description: "Take Minor Blood fallout.", type: "Minor" },
			{ description: "Help someone vulnerable with no expectation of repayment.", type: "Minor" },
			{ description: "Repair something physical —a bridge, a door, a wall, etc.— that someone needs.", type: "Minor" },
			{ description: "De-escalate a situation that would have led to bloodshed.", type: "Minor" },
			{ description: "Spare someone's life.", type: "Minor" },
			{ description: "Make penance at a site that is important to your order.", type: "Minor" },
			{ description: "Punish an NPC for wrongdoing.", type: "Minor" },
			{ description: "Meet an NPC who hates you for what you've done.", type: "Minor" },
			{ description: "Perform an act in service to your order.", type: "Minor" },
			{ description: "Bring bodily harm to those who stand against your order.", type: "Minor" },
			{ description: "Sabotage the assets of those who stand against your order.", type: "Minor" },
			{ description: "Establish a connection to a landmark that's important to your order.", type: "Minor" },
			{ description: "Witness first-hand the tragic extent of your failings.", type: "Minor" },
			{ description: "Donate needed supplies to your order.", type: "Minor" },
			{ description: "Teach someone the value of your order's philosophies.", type: "Minor" },
			{ description: "Put yourself in great danger to protect your companions.", type: "Minor" },
			{ description: "Make reparations to an NPC that you have personally wronged.", type: "Minor" },
			{ description: "Do something your order would frown upon.", type: "Minor" },
			{ description: "Rescue or assist an NPC who belongs to your order.", type: "Minor" },
			{ description: "Openly attack the enemies of your order.", type: "Minor" },
			{ description: "Refuse a desirable offer due to the restrictions of your penance.", type: "Minor" },
			{ description: "Take Major Blood fallout.", type: "Major" },
			{ description: "Convert an important NPC to your order's cause.", type: "Major" },
			{ description: "Establish continual connections between two landmarks on different tiers that are important to your order.", type: "Major" },
			{ description: "Perform an act that, if your order discovered it, would undo your penance.", type: "Major" },
			{ description: "Betray someone who really trusts you.", type: "Major" },
			{ description: "Save a landmark dedicated to your order.", type: "Major" },
			{ description: "Attack the enemies of your order when the odds are massively stacked against you.", type: "Major" },
			{ description: "Eliminate or completely undermine a faction that is opposed to your order.", type: "Major" },
			{ description: "Your order suffers a devastating setback, and you believe that it's your fault.", type: "Major" },
			{ description: "A member of your order begs you to perform an undesirable task; to refuse would be disgraceful.", type: "Major" },
			{ description: "Be truly absolved of your sins by a higher power.", type: "Zenith" },
			{ description: "Betray your order —intentionally, this time.", type: "Zenith" }
		],
		trinkets: [
			"Absolution chains (heavy)",
			"Vellum scroll bearing a record of your crimes",
			"Still-itching tattoo depicting your sins",
			"The skull of someone you loved",
			"Vial of ashes with a name on it",
			"Masonry fragment from a destroyed statue",
			"Book of handwritten, melodramatic poetry",
			"Locket depicting a beautiful one-eyed drow",
			"Ceremonial bronze Watchful Eye",
			"Brand identifying you as one of the secretive knights of the Covenant of the Fallen Tower"
		]
	}
];
