export const ResourceTags: HeartResourceTags[] = [
	{ name: "Awkward", hasVariable: false, description: "the resource is heavy or hard to carry." },
	{ name: "Beacon", hasVariable: false, description: "he resource attracts something dangerous towards its position." },
	{ name: "Deteriorating", hasVariable: false, description: " the resource is breaking down, rotting or rusting and you'll need to get it to a new owner quickly." },
	{ name: "Fragile", hasVariable: false, description: "the resource will be destroyed if dropped or damaged." },
	{ name: "Harmful", hasVariable: false, description: "the resource has the capacity to harm those who carry it via black magic, illness or strange energies." },
	{ name: "Mobile", hasVariable: false, description: "if left unattended, the resource will leave of its own accord." },
	{ name: "Niche", hasVariable: false, description: "the resource is only valuable to a very select group of people" },
	{ name: "Taboo", hasVariable: false, description: "the resource isn't accepted for barter in	most haunts (e.g. organs from heartsblooded	people, gold teeth or certain narcotics)." },
	{ name: "Volatile", hasVariable: false, description: "the resource may explode if mistreated." },
	{ name: "Block", hasVariable: false, description: "+1 Blood protection." },
	{ name: "Bloodbound", hasVariable: false, description: "Mark D4 stress to Blood to roll with mastery when using this equipment for the rest of the situation." },
	{ name: "Brutal", hasVariable: false, description: "When you roll for stress against an adversary when using this item, roll two dice and pick the highest.Multiple instances of this tag stack: if you managed to get it three times, you'd roll four dice and pick the highest when calculating stress." },
	{ name: "Conduit", hasVariable: false, description: "Mark D4 stress to Mind to roll with mastery when using this equipment for the rest of the situation." },
	{ name: "Dangerous", hasVariable: false, description: "When you inflict stress with this item and roll the maximum amount, mark D6 stress to Blood." },
	{ name: "Debilitating", hasVariable: false, description: "Once per situation, when you inflict stress with this item to one or more targets, the next attack made against them is rolled with mastery." },
	{ name: "Degenerating", hasVariable: false, description: "If you take damage from a weapon with this tag, roll Endure+[Domain] at the end of the situation. On a failure, mark D6 stress; on a partial success, mark D4 stress; on a success, mark none." },
	{ name: "Distressing", hasVariable: false, description: "When you inflict stress with this item and roll the maximum amount, mark D6 stress to Mind." },
	{ name: "Double-barreled", hasVariable: false, description: "As Reload, but you can use the item twice before reloading." },
	{ name: "Expensive", hasVariable: false, description: "When you inflict stress with this item and roll the maximum amount, mark D6 stress to Supplies. " },
	{ name: "Extreme range", hasVariable: false, description: "This item can be used at extreme range." },
	{ name: "Limited X", hasVariable: false, description: "You can use this X times before it gives out." },
	{ name: "Loud", hasVariable: false, description: "When you inflict stress with this item and roll the maximum amount, mark D6 stress to Fortune." },
	{ name: "Obscuring", hasVariable: false, description: "The bearer and any nearby allies reduce the damage of incoming and outgoing ranged weapons by 1 step." },
	{ name: "One-shot", hasVariable: false, description: "This equipment takes a very long time to prepare, so you can only use it once per situation." },
	{ name: "Piercing", hasVariable: false, description: "You cannot reduce stress inflicted by this equipment by using Blood Protection, and adversaries do not benefit from their protection value." },
	{ name: "Point-blank", hasVariable: false, description: "As Ranged, but at very close range it increases its stress dice by one step. If the shot travels far enough to spread out and dissipate, it lowers its stress dice by one step." },
	{ name: "Potent", hasVariable: false, description: "When you roll for stress removed from yourself or an ally with this item, roll two dice and pick the highest. Multiple instances of this tag stack as per the Brutal tag." },
	{ name: "Ranged", hasVariable: false, description: "This equipment can be used at range." },
	{ name: "Reload", hasVariable: false, description: "This equipment must be reloaded between uses, giving enemies a chance to close in or flee." },
	{ name: "Smoke", hasVariable: false, description: "As Obscuring, but only when the item is used, and only around the area it was used." },
	{ name: "Spread", hasVariable: false, description: "Anyone standing near the target on a successful use must roll Evade+Domain (or another applicable skill) to avoid marking stress as well. On a partial success, downgrade the stress dice by one size. NPCs caught in a blast simply take the stress." },
	{ name: "Tiring", hasVariable: false, description: "When you fail an action using this equipment, the size of its stress dice decreases by 1 for the remainder of the situation." },
	{ name: "Trusty", hasVariable: false, description: "When you roll for stress marked against a delve while using this item, roll two dice and pick the highest. Multiple instances of this tag stack as per the Brutal tag." },
	{ name: "Unreliable", hasVariable: false, description: "When you fail an action using this equipment, it cannot be used for the remainder of the situation if in a landmark or for the remainder of the journey if on a delve." },
	{ name: "Wyrd", hasVariable: false, description: "When you inflict stress with this item and roll the maximum amount, mark D6 stress to Echo." }
];
