name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install and Build
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
          ARGS: '-avz --delete'
          SOURCE: 'client/dist/'
          TARGET: ${{ secrets.TARGETDIR }}/client
