name: deploy-api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Source Cleanup
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          rm -rf ${{ secrets.SOURCEDIR }}/api-src

    - name: Copy
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "/api"
        target: ${{ secrets.SOURCEDIR }}/api-src

    - name: Build, Target Cleanup, Copy
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.SOURCEDIR }}/api-src
          nvm use 19.4.0
          npm i
          npm run build
          rm -rf ${{ secrets.TARGETDIR }}/client/main
          sudo cp -R ${{ secrets.SOURCEDIR }}/api-src/dist ${{ secrets.TARGETDIR }}/client/bwgrtools