name: deploy-client-main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-client-main.yml"
      - "client/main/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "/client/main/**"
        target: ${{ secrets.SOURCEDIR }}/client/main-src
        strip_components: 1
        rm: true

    - name: Build, Target Cleanup, Copy
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.SOURCEDIR }}/client/main-src
          nvm use 19.4.0
          npm i
          npm run build
          sudo rm -rf ${{ secrets.TARGETDIR }}/client/main
          sudo cp -R ${{ secrets.SOURCEDIR }}/client/main-src/dist ${{ secrets.TARGETDIR }}/client/main