name: deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build, Install, and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use stable
            pm2 stop yl
            cd ${{ secrets.SOURCEDIR }}/yigitlevent.com
            git pull origin main
            npm install
            npm run build
            pm2 restart yl
