name: deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy Source to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "./**"
          target: ${{ secrets.SOURCEDIR }}/yl-src
          rm: true

      - name: Build, Install, and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo rm -rf ${{ secrets.SOURCEDIR }}/yl-src
            sudo rm -rf ${{ secrets.TARGETDIR }}/yl
            sudo mkdir -p ${{ secrets.SOURCEDIR }}/yl-src
            sudo mkdir -p ${{ secrets.TARGETDIR }}/yl
            cd ${{ secrets.SOURCEDIR }}/yl-src
            nvm use node
            npm i
            npm run build
            sudo cp -r ${{ secrets.SOURCEDIR }}/yl-src/* ${{ secrets.TARGETDIR }}/yl/
            sudo pm2 delete yl || true
            cd ${{ secrets.TARGETDIR }}/yl
            sudo pm2 start "npm start" --name yl --cwd ${{ secrets.TARGETDIR }}/yl --update-env
            sudo pm2 save
