name: deploy-types

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-types.yml"
      - "@types/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Clean and Copy Types
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "@types/**"
        target: ${{ secrets.SOURCEDIR }}
        rm: true